import os

UPLOAD_FOLDER = 'static/uploads'
# config.py

DB_HOST = 'RAILWAY_PRIVATE_DOMAIN'
DB_PORT = 5432
DB_NAME = 'POSTGRES_DB'
DB_USER = 'POSTGRES_USER'
DB_PASSWORD = 'POSTGRES_PASSWORD'


# Email SMTP configuration
MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 587
MAIL_USERNAME = os.environ.get('MAIL_USERNAME')
MAIL_PASSWORD = os.environ.get('MAIL_PASSWORD')
MAIL_USE_TLS = True
